version: '3.8'

services:

  server:
    image: 'tomcat:9.0'
    container_name: server
    ports:
      - "8080:8080"
    restart: on-failure

    volumes:
      - ./target:/usr/local/tomcat/webapps

    #    depends_on:
    #      server:
    #        condition: service_healthy
    networks:
      - app
networks:
  app:
    driver: bridge