version: '3.8'

services:
  server:
    image: 'tomcat:9.0'
    container_name: server
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - ./target/help-v1.war:/usr/local/tomcat/webapps/help-service.war
